env:
  browser: true
  node: true
extends:
  - airbnb
  - prettier
  - plugin:array-func/all
parser: '@typescript-eslint/parser'
plugins:
  - prettier
  - react-hooks
  - promise
  - import
  - "@typescript-eslint"
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: .
rules:
  import/extensions:
    - error
    - never
  import/no-extraneous-dependencies: ["error", {"devDependencies": true}]
  prettier/prettier:
    - error
    - endOfLine: lf
  no-console: 0
  global-require: 0
  no-param-reassign: 0
  no-underscore-dangle:
    - error
    - allow: ['_id', '_carddict']
  camelcase:
    - error
    - properties: never
      ignoreDestructuring: true
      ignoreImports: true
      allow: ['tcgplayer_id']
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-restricted-syntax:
    - error
    - WithStatement
    - LabeledStatement
    - BinaryExpression[operator='in']
  react/jsx-filename-extension: off
  react/jsx-one-expression-per-line: off
  react/jsx-props-no-spreading: off
  react/no-unescaped-entities:
    - error
    - forbid: ['>', '"', '}']
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  import/no-commonjs: error
  no-restricted-imports:
    - error
    - patterns: ['./*', '../*']
  promise/param-names: error
  promise/no-new-statics: error
  promise/valid-params: error
  promise/prefer-await-to-then: error
  promise/prefer-await-to-callbacks: error
overrides:
  - files: ['**/*.cjs']
    rules:
      import/no-commonjs: off
  - files: ['server/**']
    rules:
      no-console: error
  - files: ['client/markdown/**/micromark-*']
    rules:
      no-use-before-define: ['error', 'nofunc']
  - files: ['server/models/**']
    rules:
      no-underscore-dangle:
        - error
        - allowAfterThis: true
  - files: ['server/one_shot_scripts/**', 'server/jobs/**']
    rules:
      no-await-in-loop: 0
